# Generated by Django 4.1.7 on 2023-02-28 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tasksubmission',
            options={'verbose_name': 'task submission', 'verbose_name_plural': 'Task submission'},
        ),
    ]
