# Generated by Django 4.1.7 on 2023-02-28 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_remove_task_attachment_task_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasksubmission',
            name='score',
        ),
    ]
