# Generated by Django 4.1.7 on 2023-02-28 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0006_alter_task_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasksubmission',
            name='text',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
