# Generated by Django 4.1.7 on 2023-02-28 09:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('courses', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='audience',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='audience'),
        ),
        migrations.AlterField(
            model_name='course',
            name='chapter',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='chapter'),
        ),
        migrations.AlterField(
            model_name='course',
            name='item',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='item'),
        ),
        migrations.AlterField(
            model_name='course',
            name='members',
            field=models.ManyToManyField(blank=True, null=True, related_name='members', to=settings.AUTH_USER_MODEL, verbose_name='members'),
        ),
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.CharField(max_length=50, verbose_name='name'),
        ),
    ]
